### ISSUE TITLE
 symbexcel-server 404

### ISSUE THREAD

**Issue by ElNiak** [ucsb-seclab/symbexcel#1]
Hello,

I noticed that the link to symbexcel-server appears to be dead. When I try to access it, I receive a 404 error message. This is preventing me from being able to use the server for my SymbExcel work.

Could you please take a look and see if there's a way to fix the link? I'm not sure if there's a new URL that I should be using or if there's some other issue.

Thank you for your help!

Best regards,

ElNiak

**Comment by ruaronicola** [comment]
Hi there,

Sorry about that, you should be able to access the symbexcel-server repo now at this url: https://github.com/ucsb-seclab/symbexcel-server.

Thanks for reaching out!

Nicola
